name: Fabrica_de_Lucro_04
on:
  schedule:
    - cron: '45 * * * *' # Bate o ponto aos 45 minutos de cada hora
  workflow_dispatch:
jobs:
  trabalhar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Executar Minerador
        env:
          STREAMR_PRIVATE_KEY: ${{ secrets.STREAMR_PRIVATE_KEY }}
        run: python bot_vitoria.py
